### Test/Train Split and Encoding
#### Elizabeth Greenan

In [69]:
import sys
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [70]:
import os
print(os.getcwd())

/Users/elizabethgreenan/Documents/DSE6311/GitHub/DSE6311/E-Cigarette-Health-Advertisement-Study/Scripts

In [71]:
# Use newly cleaned data from Nick from 4/11
e_cigarette_data = pd.read_csv("../data/cleaned_data.csv")
e_cigarette_data.head()

,Unnamed: 0,BMI,Number_of_Children,Dentist_Visit_Last_Year,Health_Insurance,Lung_Cancer_Suspected_Risk,Marijuana_Use_30_Days,Medical_Visit_Missed_Due_to_Cost,Number_of_Days_Last_Month_Poor_Health,High_Financial_Stress_Burden,...,Social_Emotional_Support,General_Health_Personal_Rating,Life_Satisfaction,Marital_Status,Sugar_Soda_Drinks_Per_Day,Sugar_Soda_Drinks_Per_Week,Sugar_Soda_Drinks_Per_Month,Non_Soda_Sugar_Drinks_Per_Day,Non_Soda_Sugar_Drinks_Per_Week,Non_Soda_Sugar_Drinks_Per_Month
0,0,22.49,0.0,1.0,1.0,NaN,NaN,0.0,0.0,0.0,...,Always,Good,Very_satisfied,Widowed,NaN,NaN,NaN,NaN,NaN,NaN
1,1,25.83,0.0,1.0,1.0,NaN,NaN,0.0,NaN,0.0,...,Always,Excellent,Very_satisfied,Married,NaN,NaN,NaN,NaN,NaN,NaN
2,2,22.53,0.0,0.0,1.0,NaN,NaN,1.0,1.0,0.0,...,Usually,Very_good,Very_satisfied,Member_of_unmarried_couple,NaN,NaN,NaN,NaN,NaN,NaN
3,3,25.09,0.0,1.0,1.0,NaN,NaN,0.0,NaN,0.0,...,Always,Excellent,Very_satisfied,Married,NaN,NaN,NaN,NaN,NaN,NaN
4,4,19.77,0.0,1.0,1.0,0.0,NaN,0.0,NaN,0.0,...,Rarely,Good,Satisfied,Never_Married,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
# Remove the Unnamed: 0 field
e_cigarette_data = e_cigarette_data.drop(columns=['Unnamed: 0'])
e_cigarette_data.head()

,BMI,Number_of_Children,Dentist_Visit_Last_Year,Health_Insurance,Lung_Cancer_Suspected_Risk,Marijuana_Use_30_Days,Medical_Visit_Missed_Due_to_Cost,Number_of_Days_Last_Month_Poor_Health,High_Financial_Stress_Burden,Sex,...,Social_Emotional_Support,General_Health_Personal_Rating,Life_Satisfaction,Marital_Status,Sugar_Soda_Drinks_Per_Day,Sugar_Soda_Drinks_Per_Week,Sugar_Soda_Drinks_Per_Month,Non_Soda_Sugar_Drinks_Per_Day,Non_Soda_Sugar_Drinks_Per_Week,Non_Soda_Sugar_Drinks_Per_Month
0,22.49,0.0,1.0,1.0,NaN,NaN,0.0,0.0,0.0,Female,...,Always,Good,Very_satisfied,Widowed,NaN,NaN,NaN,NaN,NaN,NaN
1,25.83,0.0,1.0,1.0,NaN,NaN,0.0,NaN,0.0,Male,...,Always,Excellent,Very_satisfied,Married,NaN,NaN,NaN,NaN,NaN,NaN
2,22.53,0.0,0.0,1.0,NaN,NaN,1.0,1.0,0.0,Male,...,Usually,Very_good,Very_satisfied,Member_of_unmarried_couple,NaN,NaN,NaN,NaN,NaN,NaN
3,25.09,0.0,1.0,1.0,NaN,NaN,0.0,NaN,0.0,Male,...,Always,Excellent,Very_satisfied,Married,NaN,NaN,NaN,NaN,NaN,NaN
4,19.77,0.0,1.0,1.0,0.0,NaN,0.0,NaN,0.0,Male,...,Rarely,Good,Satisfied,Never_Married,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
e_cigarette_data.shape

(457670, 35)

In [74]:
print(e_cigarette_data.columns)

Index(['BMI', 'Number_of_Children', 'Dentist_Visit_Last_Year',
       'Health_Insurance', 'Lung_Cancer_Suspected_Risk',
       'Marijuana_Use_30_Days', 'Medical_Visit_Missed_Due_to_Cost',
       'Number_of_Days_Last_Month_Poor_Health', 'High_Financial_Stress_Burden',
       'Sex', 'Has_Disability', 'Diabetic_History', 'Days_Poor_Mental_Health',
       'Age_Category', 'E_Cig_User', 'Other_Tobacco_Usage', 'Race',
       'Total_Drinks_30_days', 'Time_Since_Last_Check_Up',
       'Exercise_Outside_Work_Past_Month', 'Loneliness', 'Health_Rating',
       'Annual_Income', 'Days_Poor_Physical_Health', 'Education',
       'Social_Emotional_Support', 'General_Health_Personal_Rating',
       'Life_Satisfaction', 'Marital_Status', 'Sugar_Soda_Drinks_Per_Day',
       'Sugar_Soda_Drinks_Per_Week', 'Sugar_Soda_Drinks_Per_Month',
       'Non_Soda_Sugar_Drinks_Per_Day', 'Non_Soda_Sugar_Drinks_Per_Week',
       'Non_Soda_Sugar_Drinks_Per_Month'],
      dtype='object')

In [75]:
# Move the target/response varaible (E_Cig_User) to the end of the dataframe
# Source: https://stackoverflow.com/questions/72782872/move-a-dataframe-column-to-last-column
e_cigarette_data['E_Cig_User'] = e_cigarette_data.pop('E_Cig_User')

In [76]:
print(e_cigarette_data.columns)

Index(['BMI', 'Number_of_Children', 'Dentist_Visit_Last_Year',
       'Health_Insurance', 'Lung_Cancer_Suspected_Risk',
       'Marijuana_Use_30_Days', 'Medical_Visit_Missed_Due_to_Cost',
       'Number_of_Days_Last_Month_Poor_Health', 'High_Financial_Stress_Burden',
       'Sex', 'Has_Disability', 'Diabetic_History', 'Days_Poor_Mental_Health',
       'Age_Category', 'Other_Tobacco_Usage', 'Race', 'Total_Drinks_30_days',
       'Time_Since_Last_Check_Up', 'Exercise_Outside_Work_Past_Month',
       'Loneliness', 'Health_Rating', 'Annual_Income',
       'Days_Poor_Physical_Health', 'Education', 'Social_Emotional_Support',
       'General_Health_Personal_Rating', 'Life_Satisfaction', 'Marital_Status',
       'Sugar_Soda_Drinks_Per_Day', 'Sugar_Soda_Drinks_Per_Week',
       'Sugar_Soda_Drinks_Per_Month', 'Non_Soda_Sugar_Drinks_Per_Day',
       'Non_Soda_Sugar_Drinks_Per_Week', 'Non_Soda_Sugar_Drinks_Per_Month',
       'E_Cig_User'],
      dtype='object')

In [77]:
e_cigarette_data.shape

(457670, 35)

In [78]:
# Test/Train Split source: Used code Professor Geist provided (calcSplitRatio.py)

In [79]:
# p represents the number of parameters
def calcSplitRatio(e_cigarette_data, p = None):
    if p is None:
        p = e_cigarette_data.shape[1] - 1 # This assumes the last column is the target variable

    # Calculate the ideal number for the testing set
    test_N = (1 / np.sqrt(p)) * len(e_cigarette_data)

    # Calculate the testing proportion
    test_prop = round(test_N / len(e_cigarette_data), 2)

    # Calculate the training proportion
    train_prop = 1 - test_prop

    # Print the results
    print(f"The ideal split ratio is {train_prop}:{test_prop} training:testing")

    # Return the size of the training set proportion
    return train_prop

In [80]:
train_prop = calcSplitRatio(e_cigarette_data)

The ideal split ratio is 0.83:0.17 training:testing

In [81]:
# The training proportion is 83% and the testing proportion is 17%.

## Supervised Test/Train Split

In [82]:
# Code source: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
# Referenced code from DSE6211 (Lab 2)

# Remove the response variable
x = e_cigarette_data.drop('E_Cig_User', axis = 1)
# Want to predict the response variable
y = e_cigarette_data['E_Cig_User']
# Perform test/train split
# Random_state ensures reproducibility
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = train_prop, random_state = 1)

## Unsupervised Test/Train Split

In [83]:
# Since unsupervised does not use a response variable, the y code was removed
# Remove the response variable
x = e_cigarette_data.drop('E_Cig_User', axis = 1)
# Perform test/train split
# Random_state ensures reproducibility
x_train_unsupervised, x_test_unsupervised = train_test_split(x, train_size = train_prop, random_state = 1)

## Check results of split to ensure they are correct

In [84]:
print(x_train.shape)
print(x_test.shape)

(379866, 34)
(77804, 34)

In [85]:
print(y_train.shape)
print(y_test.shape)

(379866,)
(77804,)

In [86]:
# Confirm that the training set is approximately 83% and the test set is approximately 17%
training_ratio = len(x_train) / (len(x_train) + len(x_test))
test_ratio = len(x_test) / len(x)

print("Training ratio:", training_ratio)
print("Test ratio:", test_ratio)

Training ratio: 0.8299997815019555
Test ratio: 0.17000021849804445

In [87]:
# Confirm there is one less column, due to the removal of the response variable
x_train.head()

,BMI,Number_of_Children,Dentist_Visit_Last_Year,Health_Insurance,Lung_Cancer_Suspected_Risk,Marijuana_Use_30_Days,Medical_Visit_Missed_Due_to_Cost,Number_of_Days_Last_Month_Poor_Health,High_Financial_Stress_Burden,Sex,...,Social_Emotional_Support,General_Health_Personal_Rating,Life_Satisfaction,Marital_Status,Sugar_Soda_Drinks_Per_Day,Sugar_Soda_Drinks_Per_Week,Sugar_Soda_Drinks_Per_Month,Non_Soda_Sugar_Drinks_Per_Day,Non_Soda_Sugar_Drinks_Per_Week,Non_Soda_Sugar_Drinks_Per_Month
410506,22.81,0.0,0.0,1.0,0.0,NaN,1.0,NaN,NaN,Male,...,Unknown,Very_good,Unknown,Divorced,NaN,NaN,NaN,NaN,NaN,NaN
357202,28.34,0.0,1.0,1.0,NaN,NaN,0.0,NaN,0.0,Female,...,Always,Good,Very_satisfied,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
207655,41.05,0.0,0.0,1.0,NaN,0.0,0.0,5.0,0.0,Female,...,Always,Very_good,Satisfied,Widowed,NaN,NaN,2.0,NaN,NaN,NaN
357855,26.04,0.0,1.0,1.0,NaN,NaN,0.0,NaN,0.0,Male,...,Usually,Excellent,Satisfied,Married,NaN,NaN,NaN,NaN,NaN,NaN
381841,26.63,0.0,1.0,1.0,NaN,NaN,0.0,NaN,0.0,Male,...,Unknown,Good,Satisfied,Never_Married,NaN,NaN,NaN,NaN,NaN,NaN

## Encoding

In [88]:
# Dummy encoding for the categorical variables
# Source: https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html

In [89]:
# Supervised
x_train = pd.get_dummies(x_train, drop_first = True)
x_test = pd.get_dummies(x_test, drop_first = True)

In [90]:
# Check that the columns in both training and test set match
set(x_train.columns) == set(x_test.columns)

True

In [91]:
# Unsupervised
x_train_unsupervised = pd.get_dummies(x_train_unsupervised, drop_first = True)
x_test_unsupervised = pd.get_dummies(x_test_unsupervised, drop_first = True)

In [92]:
# Check that the columns in both training and test set match
set(x_train_unsupervised.columns) == set(x_test_unsupervised.columns)

True